name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - run: npm ci
      - run: npm run prisma
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      - run: npm start
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          QUERY_BATCH_SIZE: 32766
      - run: npm start
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
